# Generated by Django 3.2.9 on 2021-11-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_eng', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=16)),
                ('website_url', models.URLField()),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='SpecType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'spec_types',
            },
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model')),
            ],
            options={
                'db_table': 'trims',
            },
        ),
        migrations.CreateModel(
            name='SpecInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_eng', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('multi_values', models.CharField(blank=True, default='', max_length=32)),
                ('spec_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.spectype')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.trim')),
            ],
            options={
                'db_table': 'spec_infos',
            },
        ),
    ]
